
package swing;
import database.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class Teacher extends javax.swing.JFrame {
 Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Teacher() {
        initComponents();
           con = DBconnect.connect();

        //table load krna eka
        tableload();
    }
    
     public void tableload() {

        try {
            String sql = "SELECT tid,tname,tphone,tnic,tgen,tbtyp,tbname,tbidate,tbrdate,tsate from teacher";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            ctable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepnel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        stockbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cprintbtn = new javax.swing.JButton();
        caddbtn = new javax.swing.JButton();
        cupdatebtn = new javax.swing.JButton();
        cdelbtn = new javax.swing.JButton();
        cclerbtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        tidbox1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tnamebox = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tgenbox = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        tbooktybox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        tbnamebox = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tsteabox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        tphonebox = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tnicbox = new javax.swing.JTextField();
        brdatebox = new com.toedter.calendar.JDateChooser();
        bidatebox = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidepnel.setBackground(new java.awt.Color(23, 35, 51));
        sidepnel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_home_48px_1.png"))); // NOI18N
        sidepnel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 30));

        jButton4.setText("Home");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        sidepnel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, 20));

        jPanel2.setBackground(new java.awt.Color(71, 120, 190));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_close_window_30px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 30, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/206897 (1).png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 70, -1));

        jButton5.setText("Teachers");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/png-transparent-computer-icons-student-school-student-angle-people-logo-thumbnail (1).png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 2, 60, -1));

        jButton6.setText("Students");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 90, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/29302 (1).png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 60, 50));

        jButton7.setText("Books");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 90, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_small_business_48px_1.png"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 80, 50));

        stockbtn.setText("Stock");
        stockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockbtnActionPerformed(evt);
            }
        });
        jPanel2.add(stockbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 90, 20));

        jPanel3.setBackground(new java.awt.Color(71, 120, 190));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/images (1).png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teachers Info");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 4, 310, 60));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 280, 10));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        cprintbtn.setText("Print");
        jPanel3.add(cprintbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, -1));

        caddbtn.setText("Add");
        caddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddbtnActionPerformed(evt);
            }
        });
        jPanel3.add(caddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        cupdatebtn.setText("Update");
        cupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupdatebtnActionPerformed(evt);
            }
        });
        jPanel3.add(cupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        cdelbtn.setText("Delete");
        cdelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdelbtnActionPerformed(evt);
            }
        });
        jPanel3.add(cdelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        cclerbtn.setText("Clear");
        cclerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cclerbtnActionPerformed(evt);
            }
        });
        jPanel3.add(cclerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 255));
        jLabel16.setText("Teacher Number");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        tidbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidbox1ActionPerformed(evt);
            }
        });
        jPanel3.add(tidbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 255, 255));
        jLabel17.setText("Name");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel3.add(tnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 270, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 255, 255));
        jLabel27.setText("Gender");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        tgenbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(tgenbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 255, 255));
        jLabel24.setText("Book Type");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        tbooktybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classics", "Novel", "Horror", "Fantasy", "Science fiction", "History", "Short story" }));
        tbooktybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbooktyboxActionPerformed(evt);
            }
        });
        jPanel3.add(tbooktybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 130, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 255, 255));
        jLabel20.setText("Book name");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
        jPanel3.add(tbnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 270, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 255, 255));
        jLabel21.setText("Book Issue date");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 255, 255));
        jLabel22.setText("Book Return date");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 255, 255));
        jLabel23.setText("current state");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        tsteabox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book Issued", "Book returned", " " }));
        jPanel3.add(tsteabox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 130, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 255, 255));
        jLabel19.setText("Phone Number");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel3.add(tphonebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 270, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 255, 255));
        jLabel26.setText("NIC Number");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel3.add(tnicbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 270, 30));

        brdatebox.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(brdatebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        bidatebox.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(bidatebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));

        ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ctable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sidepnel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(sidepnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //page eka load krnna constructor ekk hdghda
        home h1 = new home();
        h1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //page eka load krnna constructor ekk hdghda
        stu s1 = new stu();
        s1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //page eka load krnna constructor ekk hdghda
        Book e1 = new Book();
        e1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void stockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockbtnActionPerformed
        // TODO add your handling code here:

        supli st = new supli();
        st.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stockbtnActionPerformed

    private void ctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctableMouseClicked
        // TODO add your handling code here:

        //value eka select krma box walta ynna
        int r = ctable.getSelectedRow();

        String id = ctable.getValueAt(r, 0).toString();
        String name = ctable.getValueAt(r, 1).toString();
        String phone = ctable.getValueAt(r, 2).toString();
        String nic = ctable.getValueAt(r, 3).toString();
        String gen = ctable.getValueAt(r, 4).toString();
        String qty = ctable.getValueAt(r, 5).toString();
        String amt = ctable.getValueAt(r, 6).toString();
        String dis = ctable.getValueAt(r, 7).toString();
        String tot = ctable.getValueAt(r, 8).toString();
        String stat = ctable.getValueAt(r, 9).toString();

         tidbox1.setText(id);
        tnamebox.setText(name);
        tphonebox.setText(phone);;
        tnicbox.setText(nic);;
        tgenbox.setSelectedItem(gen);
        tbooktybox.setSelectedItem(qty);
        tbnamebox.setText(amt);
        bidatebox.setDateFormatString(dis);
        brdatebox.setDateFormatString(tot);
        tsteabox.setSelectedItem(stat);
    }//GEN-LAST:event_ctableMouseClicked

    private void cclerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cclerbtnActionPerformed
        // TODO add your handling code here:

         tidbox1.setText("");
        tnamebox.setText("");
        tphonebox.setText("");;
        tnicbox.setText("");;
        tgenbox.setSelectedItem("");
        tbooktybox.setSelectedItem("");
        tbnamebox.setText("");
        bidatebox.setDateFormatString("");
        brdatebox.setDateFormatString("");
        tsteabox.setSelectedItem("");
        
        
    }//GEN-LAST:event_cclerbtnActionPerformed

    private void cdelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdelbtnActionPerformed
        // TODO add your handling code here:

        int x = JOptionPane.showConfirmDialog(null, "Do you really want to Delete this");
        //update krna oneda ahnwa
        if (x == 0) {
            String id = tidbox1.getText();

            String sql = "DELETE from teacher where tid = '" + id + "'";

            //loku wedak krddi try catch ekk athulta danwa
            try {
                pst = con.prepareStatement(sql);
                pst.execute();
                tableload();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cdelbtnActionPerformed

    private void cupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupdatebtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to update");
        //update krna oneda ahnwa
        if (x == 0) {
       
        String tid = tidbox1.getText();
        String tname = tnamebox.getText();
        String tphone = tphonebox.getText();
        String tnic = tnicbox.getText();
        String tbgen = tgenbox.getSelectedItem().toString();
        String tbty = tbooktybox.getSelectedItem().toString();
        String tbname = tbnamebox.getText();
        String tbidate = ((JTextField)bidatebox.getDateEditor().getUiComponent()).getText();
        String tbrdate = ((JTextField)brdatebox.getDateEditor().getUiComponent()).getText();
        String tsate = tsteabox.getSelectedItem().toString();
        
        ;
            String sql = "UPDATE teacher SET tname = '" + tname + "' , tphone = '" + tphone + "' , tnic = '" + tnic + "' , tgen = '" + tbgen + "' , tbtyp = '" + tbty + "' , tbname = '" + tbname + "' , tbidate = '" + tbidate + "' , tbrdate = '" + tbrdate + "', tsate = '" + tsate + "' where tid = '" + tid + "'";

            //loku wedak krddi try catch ekk athulta danwa
            try {
                pst = con.prepareStatement(sql);
                pst.execute();

                tableload();

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cupdatebtnActionPerformed

    private void caddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddbtnActionPerformed

        //data base add part
        
        String sid = tidbox1.getText();
        String sname = tnamebox.getText();
        String grade = tphonebox.getText();
        String clas = tnicbox.getText();
        String sgen = tgenbox.getSelectedItem().toString();
        String btype = tbooktybox.getSelectedItem().toString();
        String bname = tbnamebox.getText();
        String Bidae = ((JTextField)bidatebox.getDateEditor().getUiComponent()).getText(); 
        String Brdae = ((JTextField)brdatebox.getDateEditor().getUiComponent()).getText(); 
        String Cstet = tsteabox.getSelectedItem().toString();
        ;
        

        try {
            String q = "INSERT INTO teacher (tname,tphone,tnic,tgen,tbtyp,tbname,tbidate,tbrdate,tsate) values ('" + sname + "','" + grade + "','" + clas + "','" + sgen + "','" + btype + "','" + bname + "','" + Bidae + "','" + Brdae + "','" + Cstet + "')";
            pst = con.prepareStatement(q);
            pst.execute();//execute krnwa database ekaata
            //load table
            tableload();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_caddbtnActionPerformed

    private void tidbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidbox1ActionPerformed

    private void tbooktyboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbooktyboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbooktyboxActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser bidatebox;
    private com.toedter.calendar.JDateChooser brdatebox;
    private javax.swing.JButton caddbtn;
    private javax.swing.JButton cclerbtn;
    private javax.swing.JButton cdelbtn;
    private javax.swing.JButton cprintbtn;
    private javax.swing.JTable ctable;
    private javax.swing.JButton cupdatebtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel sidepnel;
    private javax.swing.JButton stockbtn;
    private javax.swing.JTextField tbnamebox;
    private javax.swing.JComboBox<String> tbooktybox;
    private javax.swing.JComboBox<String> tgenbox;
    private javax.swing.JTextField tidbox1;
    private javax.swing.JTextField tnamebox;
    private javax.swing.JTextField tnicbox;
    private javax.swing.JTextField tphonebox;
    private javax.swing.JComboBox<String> tsteabox;
    // End of variables declaration//GEN-END:variables
}
